services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend-ventas:
    image: 905418066245.dkr.ecr.us-east-1.amazonaws.com/devops-u2-backend-ventas
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - db_data:/var/lib/mysql
      
  backend-despachos:
    image: 905418066245.dkr.ecr.us-east-1.amazonaws.com/devops-u2-backend-despachos
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - db_data:/var/lib/mysql
  frontend:
      image: 905418066245.dkr.ecr.us-east-1.amazonaws.com/devops-u2-frontend:latest
      ports:
        - "80:80"
      environment:
        - BACKEND_IP=${EC2_BACKEND_PRIVATE_IP}
volumes:
  db_data: