#Despliegue
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-despacho
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-despacho
  template:
    metadata:
      labels:
        app: backend-despacho
    spec:
      containers:
        - name: backend-despacho
          image: 066675147695.dkr.ecr.us-east-1.amazonaws.com/innovatech-backend-despacho:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/innavatech_db
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom: # <- CAMBIO A SECRETO
                secretKeyRef:
                  name: db-credentials
                  key: mysql-root-password

---
#Service
apiVersion: v1
kind: Service
metadata:
  name: backend-despacho
spec:
  selector:
    app: backend-despacho
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
