name: Despliegue EKS en AWS

on:
  push:
    branches:
      - develop-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      CLUSTER: innovatech-cluster
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      
      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login en ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Obtener el AWS ACCOUNT ID
        run: |
          echo "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV
      
      - name: Definir las URL de los ECR
        run: |
          echo "BACKEND_VENTAS_ECR=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/innovatech-backend-ventas" >> $GITHUB_ENV
          echo "BACKEND_DESPACHOS_ECR=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/innovatech-backend-despacho" >> $GITHUB_ENV
          echo "FRONTEND_ECR=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/innovatech-frontend" >> $GITHUB_ENV

      - name: Construir el backend de ventas
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $BACKEND_VENTAS_ECR:${GITHUB_SHA} \
            ./back-Ventas_SpringBoot/Springboot-API-REST \
            --load

      - name: Push del backend de ventas
        run: |
          docker push $BACKEND_VENTAS_ECR:${GITHUB_SHA}

      - name: Construir del backend de despachos
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $BACKEND_DESPACHOS_ECR:${GITHUB_SHA} \
            ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO \
            --load

      - name: Push del backend despachos
        run: |
          docker push $BACKEND_DESPACHOS_ECR:${GITHUB_SHA}

      - name: Construir el frontend
        run: |
          docker buildx build \
           --platform linux/amd64 \
            -t $FRONTEND_ECR:${GITHUB_SHA} \
            ./front_despacho \
            --load

      - name: Push del frontend
        run: |
          docker push $FRONTEND_ECR:${GITHUB_SHA}

      - name: Instalar kubectl
        uses: azure/setup-kubectl@v4
      
      - name: Conectar el EKS
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER

      - name: Aplicar kubernetes
        run: |
          kubectl apply -f infra/k8s/

      - name: Actualizar nombre de la imagen del backend_despacho
        run: |
          kubectl set image deployment/backend-despacho \
          backend-despacho=$BACKEND_DESPACHOS_ECR:${GITHUB_SHA}

      - name: Actualizar nombre de la imagen del backend_venta
        run: |
          kubectl set image deployment/backend-ventas \
          backend-ventas=$BACKEND_VENTAS_ECR:${GITHUB_SHA}

      - name: Actualizar nombre de la imagen del frontend
        run: |
          kubectl set image deployment/frontend \
          frontend=$FRONTEND_ECR:${GITHUB_SHA}
      
      - name: Esperar la recarga de los servicios
        run: |
          kubectl rollout status deployment/backend-despacho
          kubectl rollout status deployment/backend-ventas
          kubectl rollout status deployment/frontend

      - name: Obtener la IP del frontend
        run: |
          kubectl get service frontend -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'