name: Despliegue EKS en AWS

on:
  push:
    branches:
      - develop-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      CLUSTER: innovatech-cluster
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      
      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login en ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Obtener el AWS ACCOUNT ID
        run: |
          echo "ACCOUNT_ID-$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV
      
      - name: Definir las URL de los ECR
        run: |
          echo "BACKEND_VENTAS_ECR=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/backend_ventas" >> $GITHUB_ENV
          echo "BACKEND_DESPACHOS_ECR=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/backend_despachos" >> $GITHUB_ENV
          echo "FRONTEND_ECR=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend_innovatech" >> $GITHUB_ENV

      - name: Construir el backend de ventas
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $BACKEND_VENTAS_ECR:${GITHUB_SHA} \
            ./back-Ventas_SpringBoot/Springboot-API-REST \
            --load
      - name: Push del backend de ventas
          docker push $BACKEND_VENTAS_ECR:${GITHUB_SHA}

      - name: Construir del backend de despachos
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $BACKEND_DESPACHOS_ECR:${GITHUB_SHA} \
            ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO \
            --load
      - name: Push del backend despachos
        run: |
          docker push $BACKEND_DESPACHOS_ECR:${GITHUB_SHA}

      - name: Construir el frontend
        run: |
          docker buildx build \
           --platform linux/amd64 \
            -t $FRONTEND_ECR:${GITHUB_SHA} \
            ./front_despacho \
            --load
      - name: Push del frontend
          docker push $FRONTEND_ECR:${GITHUB_SHA}

      - name: Instalar kubernet
        uses: azure/setup-kubecrl@v4
      
      - name: Conectar el EKS
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER
      - name: Aplicar kubernet
        run: |
          kubectl apply -f infra/k8s/

      - name: Actualizar nombre de la imagen del backend_despacho.yml
        run: |
          kubectl set image deployment/back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO \
          backend=$BACKEND_DESPACHOS_ECR:${GITHUB_SHA}

      - name: Actualizar nombre de la imagen del backend_venta.yml
        run: |
          kubectl set image deployment/backend \
          backend=$BACKEND_VENTAS_ECR:${GITHUB_SHA}

      - name: Actualizar nombre de la imagen del frontend.yml
        run: |
          kubectl set image deployment/frontend \
          frontend=$FRONTEND_ECR:${GITHUB_SHA}
      
      - name: Esperar la recarga del backend
        run: |
          kubectl rollout status deployment/backend
      - name: Esperar la recarga del frontend
        run: |
          kubectl rollout status deployment/frontend

      - name: Obtener le IP del frontend
        run: |
          kubectl get service frontend -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'    
  # Despliegue en EC2 Backend (¡Haciendo salto a través del Frontend!)
  deploy-backend:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Copiar docker-compose al EC2 Backend (Vía Proxy)
        uses: appleboy/scp-action@v0.1.4
        with:
          proxy_host: ${{ secrets.EC2_FRONTEND_IP }}
          proxy_username: ec2-user
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.EC2_BACKEND_PRIVATE_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.back.yml"
          target: "/home/ec2-user/"

      - name: Ejecutar despliegue en EC2 Backend (Vía Proxy)
        uses: appleboy/ssh-action@v0.1.7
        with:
          proxy_host: ${{ secrets.EC2_FRONTEND_IP }}
          proxy_username: ec2-user
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.EC2_BACKEND_PRIVATE_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Configurar AWS dentro del EC2 para poder bajar imágenes
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
            aws configure set region us-east-1

            # 2. Login y Variables
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}
            export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            export MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}

            # 3. Despliegue
            docker-compose -f docker-compose.back.yml down
            docker-compose -f docker-compose.back.yml pull
            docker-compose -f docker-compose.back.yml up -d

  # Despliegue directo en EC2 Frontend usando docker-compose
  deploy-frontend:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Copiar docker-compose al EC2 Frontend
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_FRONTEND_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.front.yml"
          target: "/home/ec2-user/"

      - name: Ejecutar despliegue en EC2 Frontend
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_FRONTEND_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Configurar AWS dentro del EC2 Frontend
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
            aws configure set region us-east-1

            # 2. Login y Variables
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}
            export EC2_BACKEND_PRIVATE_IP=${{ secrets.EC2_BACKEND_PRIVATE_IP }}

            # 3. Despliegue
            docker-compose -f docker-compose.front.yml down
            docker-compose -f docker-compose.front.yml pull
            docker-compose -f docker-compose.front.yml up -d